export const CUSTOMERSWRKEYS = {
    customerKey: "CUSTOMER_CREDENTIALS",
    forgotPassword: "CUSTOMER_FORGOT_PASSWORD",
    changePassword: 'CUSTOMER_CHANGE_PASSWORD',
    createParcel: 'CUSTOMER_CREATE_PARCEL',
    countParcel: 'CUSTOMER_COUNT_PARCEL',
    companyRevenue: 'COMPANY_REVENUE',
    parcelRange: 'PARCEL_RANGE',
    parcelsAll: 'PARCELS_ALL',
    countCustomers: 'COUNT_CUSTOMERS',
    editParcelsId: 'EDIT_PARCELS_ID',
    deliveredParcels: 'DELIVERED_PARCELS',
    lateParcels: 'LATE_PARCELS',
    dispatchersAll: 'DISPATCHERS_ALL',
    fetchReviews: 'FETCH_REVIEWS',
    transactions: 'TRANSACTIONS',
    billingInvoice: 'BILLING_INVOICE',
    activeShipmentsCount: 'ACTIVE_SHIPMENTS_COUNT',
    todayRevenue: 'TODAY_REVENUE',
    searchCustomers: 'SEARCH_CUSTOMERS',
    searchDispatchers: 'SEARCH_DISPATCHERS',
    searchAdministrators: 'SEARCH_ADMINISTRATORS',
    searchTransactions: 'SEARCH_TRANSACTIONS',
    searchMessages: 'SEARCH_MESSAGES',
    searchReviews: 'SEARCH_REVIEWS',
    viewParcels: 'VIEW_PARCELS',
    editParcels: 'EDIT_PARCELS',
    deleteParcels: 'DELETE_PARCELS',
    viewCustomers: 'VIEW_CUSTOMERS',
    viewDispatcher: 'VIEW_DISPATCHER',
    editDispatcher:'EDIT_DISPATCHER',
    deleteDispatcher: 'DELETE_DISPATCHER',
    deleteCustomer: 'DELETE_CUSTOMER',
    viewStaff: 'VIEW_STAFF',
    editStaf: 'EDIT_STAFF',
    deleteStaff: 'DELETE_STAFF', 
    business: 'BUSINESS'
}