export const STAFFSWRKEYS = {
    staffKey: 'STAFF_CREDENTIALS',
    adminKey: 'ADMIN_INFO', 
    forgetPasswordKey: 'FORGET_PASSWORD_KEY',
    changePassword: 'CHANGE_PASSWORD_KEY',
    createCustomer: 'CREATE_CUSTOMER',
    createStaff: 'CREATE_STAFF',
    fetchStaff: 'FETCH_STAFF',
    createDispatcher: 'CREATE_DISPATCHER',
    fetchCustomers: 'FETCH_CUSTOMERS',
    countDispatcher: 'COUNT_DISPATCHER',
    countStaff: 'COUNT_STAFF',
    accountVerify: 'ACCOUNT_VERIFY', 
    getBankAccount: 'GET_BANK_ACCOUNT',
    cardVerify: 'CARD_VERIFY',
    locations: 'LOCATIONS',
    fetchLocations: 'FETCH_LOCATIONS',
    postDistancePricing: 'POST_DISTANCE_PRICING',
    getDistancePricing: 'GET_DISTANCE_PRICING',
    deleteStaff: 'DELETE_STAFF', 
    deleteDispatcher: 'DELETE_DISPATCHER',
    deleteAccount: 'DELETE_ACCOUNT',
    deleteMessages: 'DELETE_MESSAGES',
    deleteDistancePricing: 'DELETE_DISTANCE_PRICING',
    deleteLocations: 'DELETE_LOCATIONS',
    deleteCustomer: 'DELETE_CUSTOMER',
    deletePreference: 'DELETE_PREFERENCE',
    deleteClassicPricing: 'DELETE_CLASSIC_PRICING'

}